### ISSUE TITLE
Allow the user to specify the used target directory manually

### ISSUE THREAD

**Issue by xFrednet** [rust-marker/marker#205]
`cargo-marker` requires a target directory to fetch lint crates and to compile them. Usually, it extracts the default target location from the `cargo metadata` command. However, a user might want to manually specify it instead.

I believe the best solution for this, would be to add a new field to marker's configuration under the `workspace.metadata.marker` section in `Cargo.toml`

```toml
[workspace.metadata.marker]
target_dir = "./target"
```
