### ISSUE TITLE
Allow the specification of lint crates in a file (local path and git)

### ISSUE THREAD

**Issue by xFrednet** [rust-marker/marker#81]
Currently, the lint crates have to be specified via console arguments. In a real world applications users most likely have a set of crates they want to run every time. Therefore, I suggest specifying lint crates in a file like Cargo does for dependencies.

There are several design decisions as part of this issue:
1. Which sources should be allowed?
    * I suggest mimicking the cargo format, as it has proven to work and users are used to it by now. This would mean supporting: git, path and version dependencies
2. Where should this information be specified, in `Cargo.toml` or a new `marker.toml` file?

---

Generally see: https://doc.rust-lang.org/cargo/commands/index.html for cargo comments and documentation

**Comment by xFrednet** [comment]
@Niki4tap I created an issue for this feature and for discussions

Some information:
* `cargo install` sadly only works with binaries, which is sad since that could have handled all the source resolution magic for us
* Cargo will warn about weird headers in the `Cargo.toml` file, but metadata headers are allowed like: `[workspace.metadata.marker.lints]`

This information was gathered by @Niki4tap, thank you!

**Comment by Niki4tap** [comment]
Tasks:
- [ ] Initial implementation (will be covered soon in a PR)
- [ ] Support git source fetching
- [ ] (Hard) Support registries
- [ ] Support features
- [ ] (Optional/Hard) Support lint configuration 
- [ ] (Need discussion) Use `cargo` library to discover nested configurations in workspaces.

**Comment by Niki4tap** [comment]
Last point needs a bit of explanation, imagine:
`Cargo.toml`:
```toml
[workspace]
members = [
    "member_a",
    "member_b"
]

[workspace.metadata.marker.lints]
lint_a = { path = "lint_a" }
```

Do we want to give the ability for `member_a` to override the lints supplied in the virtual manifest (add new ones)?
Maybe with `member_a/Cargo.toml`:
```toml
[package]
# your usual keys...

[package.metadata.marker.lints]
# Should we allow adding more lints here?
lint_b = { path = "../lint_b" }
# Should `lint_a` still apply for `member_a`?
```

**Comment by Niki4tap** [comment]
Additionally, using the `cargo` library would simplify source fetching and crate building a lot. The drawback for this, is that `cargo` library is unstable (and will never stabilize), just like rustc internals.

**Comment by xFrednet** [comment]
Thank you @Niki4tap!

> (Hard) Support registries

I think this item will also be blocked, until v0.0.1 can be published to crates.io, since we can't upload a lint crate, without having `marker_api` on `crates.io` as well

> (Optional/Hard) Support lint configuration

That would be something cool to see. Though, I'd move it to a new issue.

> Cargo library

Development on cargo has slowed down AFAIK. So while this'll add to the maintenance cost, I'd be fine with it if it simplifies the code significantly. I fear that we'll have a weird mix of calling cargo commands where possible and link to it directly where not.

> Do we want to give the ability for member_a to override the lints supplied in the virtual manifest (add new ones)?

This is an important question, maybe we could have the restriction that only the main `Cargo.toml` can specify lints. Crates can just enable lints they don't want. This limitation can be relaxed later on. That would be my take, for a simpler solution. Clippy only reads the main `clippy.toml` file and I don't know of anyone requesting this to be more specific. If someone really needs that, they could first navigate into the crate directory and then run `cargo marker`

Maybe [dylint](https://github.com/trailofbits/dylint) could be an interesting example. It's a tool for custom rust lints, though the user has to directly interact with rustc. From the README, it looks like they only look in the main `Cargo.toml`. 

What are your thoughts on these topics?

**Comment by Niki4tap** [comment]
> I think this item will also be blocked, until v0.0.1 can be published to crates.io, since we can't upload a lint crate, without having `marker_api` on crates.io as well

Oh, yeah, good point, feel free to extract this into a separate issue.

> That would be something cool to see. Though, I'd move it to a new issue.

Yep, I was thinking adding a new field, something like:
```toml
[workspace.metadata.marker.lints.lint_a]
path = "lint_a"
config = { ... }
```

And passing raw toml `Value` to the lint somehow (maybe adding a function to `LintPass`), but again, that comes with its own issues, and a dependency on `toml_edit` for lints :sweat_smile:, so you're right about moving this.

> Maybe [dylint](https://github.com/trailofbits/dylint) could be an interesting example. It's a tool for custom rust lints, though the user has to directly interact with rustc. From the README, it looks like they only look in the main `Cargo.toml`.

I haven't look that much into it so far, but I'm aware of it, and yes, afaik you're correct that looks only in the root `Cargo.toml`.

> What are your thoughts on these topics?

For me it would ideally look like this:
`Cargo.toml`:
```toml
[workspace]
members = [
    "member_a",
    "member_b"
]

[workspace.metadata.marker.lints]
lint_a = { ... } # this isn't possible to override by workspace members
```

`member_a/Cargo.toml`:
```toml
[package]
# ...

[package.metadata.marker.lints]
lint_a = { ... } # <- this is an error
lint_b = { ... } # but adding new lints is ok (`lint_b` won't apply to `member_b`)
```

So the structure would be:
```
root: lint_a
|
|--- member_a: lint_b
|
|--- member_b: -
```

and then after cascading:
```
member_a: lint_a, lint_b
member_b: lint_a
```

But that requires a lot of work, and I'm probably just overthinking it :sweat_smile:, so I'm fine with root config being the only one for now :)
